version: "2"

services:
 ms-n:
  image: springtest1
  ports: 
  - "8081:8080"
 ms-fa:
  image: springtest1
  ports: 
  - "8082:8080"

 ms-bp:
  image: springtest1
  ports: 
  - "8083:8080"


