version: '3'
services:
  fachlicheradministrator:
    image: fachlicheradministrator
    ports:
      - 8080
    networks:
      - front-tier-fa

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - fachlicheradministrator
    networks:
      - front-tier-fa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  front-tier-fa:
    driver: bridge
