version: '3'
services:
  bezugsperson:
    image: bezugsperson
    ports:
      - 8080
    networks:
      - front-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - bezugsperson
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  front-tier:
    driver: bridge
